defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "CASino"
    footer_text: "Powered by <a href=\"http://rbcas.com/\">CASino</a>"
  authenticators:
    static:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser:
            password: "foobar123"
            name: "Test User"
            game:
              - "StarCraft 2"
              - "Doto"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
