defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  authenticators:
    static_1:
      class: "CASinoCore::Authenticator::Static"
      options:
        users:
          testuser:
            password: "foobar123"
            name: "Test User"
    static_2:
      class: "CASinoCore::Authenticator::Static"
      options:
        users:
          example:
            password: "dito123"
            name: "Test User"

development:
  <<: *defaults

test:
  <<: *defaults
