defaults: &defaults
  service_ticket:
    lifetime_unconsumed: 299
  authenticators:
    static_1:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser:
            password: "foobar123"
            name: "Test User"
    static_2:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          example:
            password: "dito123"
            name: "Test User"

development:
  <<: *defaults

test:
  <<: *defaults
